### ISSUE TITLE
jsoncpp problem and demo problem

### ISSUE THREAD

**Issue by rbbg** [nsomani/constraint-controller-library#2]
Hi,

I was just trying to build and run the project when I ran into this build error: `json/json.h: No such file or directory` which was fixed it by changing the includes to:
`#include <jsoncpp/json/json.h>`

However, the demo's still don't work. I see the visualization coming up, and when I run 
`./run_demo models/json/cup_grasping_side_collision_constraint.json` the robot first jumps to what looks like an initial pose, and then it jumps into a self collision and stays there. Console output:

```
robot_name comau
workcell_model_id 0
set joints for comau
set joints for comau
runtime: 20874
runtime: 51274
Move failed
runtime: 51267
Move failed
runtime: 1416
Move failed
```

after a while:

```
runtime: 1673
runtime: 1598
runtime: 1603
runtime: 1636
```
The other demo's show similar behavior and output. Not sure if this is related to jsoncpp (I would doubt it) so perhaps this is a separate issue.

**Comment by nsomani** [comment]
Hi,

This is likely an issue with NLOpt. What OS are you using? The default version for NLOpt on 16.04 is different from the one on 14.04.

**Comment by rbbg** [comment]
I am on 14.04.5, NLOpt version 2.4.1

**Edit:** I have just updated to version 2.4.2, which is the latest and default for 16.04, but the problem persists.

**Comment by rbbg** [comment]
I have just updated to version 2.4.2, which is the latest and default for 16.04, but the problem persists.

**Comment by nsomani** [comment]
1604 has some issues with runtime, but still works for me. 
It should work on 14.04 with the default NLOpt version. I will take a look at it.

**Comment by nsomani** [comment]
I updated some model files. Can you please check if any of the demos work for you, especially the ones without collision avoidance (e.g. plane_constraint.json)?

**Comment by rbbg** [comment]
I pulled and rebuilt but the problem persists. Anything else I can try to track down the problem? With the lwr model loaded I also saw some `nlopt roundoff-limited` messages coming up in the terminal.

**Comment by nsomani** [comment]
I'm trying to reproduce the issue, but haven't been successful so far. I tried with a fresh docker installation, and it seems to work. You can see the attached Dockerfile to check if you did something differently. Another option is to increase the `"max-time": 50e-3` to something higher (100e-3 or 150e-3) if you have a slower machine.

Note: For running the demo from docker, you have to start the visualization `sh coach-racer7-cup.sh` 
from outside docker, and adjust the `"coach-IP": "localhost"` in the
 json files to your host IP.

[Dockerfile.txt](https://github.com/nsomani/constraint-controller-library/files/613527/Dockerfile.txt)

**Comment by nsomani** [comment]
the jsoncpp errors should be fixed now. do you still have issues with the demo?

**Comment by rbbg** [comment]
The issues are still there, but I did build and run a docker image and that did show some different behavior (like you said it would), so the problems are likely related to my system.

**Comment by rbbg** [comment]
I managed to fix the problem. My `LC_NUMERIC` locale environment variable was set to `LC_NUMERIC=nl_NL.UTF-8`, which uses a comma separator. Changing that to `us_EN.UTF-8` (a period separator) fixes the problem.
